image:
  file: .gitpod.dockerfile
tasks:
- init: |
    NPROC=6 # 6 threads seems to be the limit to avoid OOM.
    git clone https://github.com/intel-isl/Open3D-ML.git /workspace/Open3D-ML
    python -m pip install -r /workspace/Open3D-ML/requirements-tensorflow.txt
    python -m pip install -r /workspace/Open3D-ML/requirements-torch.txt
    source util/ci_utils.sh
    install_docs_dependencies
    mkdir build
    cd build
    cmake \
      -DCMAKE_BUILD_TYPE=Release \
      -DBUNDLE_OPEN3D_ML=ON \
      -DOPEN3D_ML_ROOT=/workspace/Open3D-ML \
      -DBUILD_TENSORFLOW_OPS=ON \
      -DBUILD_PYTORCH_OPS=ON \
      .. && make -j $NPROC && make install-pip-package && cd ../docs && python make_docs.py --execute_notebooks=auto --sphinx
  command: | # start webserver watching the docs and change to build dir
    npx browser-sync start --server "docs/_out/html" --watch &
    cd build
ports:
  # open the browser with the documentation
  - port: 3000
    onOpen: open-preview
github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
